<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="DetailsViewDemo.aspx.cs" Inherits="DataControlsDemonstration.DetailsViewDemo" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:DetailsView ID="dvEmployee" runat="server"
                Height="50px" Width="125px"
                AutoGenerateRows="false" DataKeyNames="EmployeeID" DataSourceID="EmployeeDetailsDataSource"

                AutoGenerateEditButton="true" AutoGenerateDeleteButton="true">
                <Fields>
                    <asp:BoundField DataField="EmployeeID" HeaderText="Employee ID" ReadOnly="true" />
                    <asp:BoundField DataField="FullName" HeaderText="Full Name" />
                    <asp:BoundField DataField="Email" HeaderText="Email" />
                    <asp:BoundField DataField="Mobile" HeaderText="Mobile" />
                    <asp:BoundField DataField="Gender" HeaderText="Gender" />
                    <asp:BoundField DataField="Salary" HeaderText="Salary" DataFormatString="{0:C}" />
                    <asp:CheckBoxField DataField="IsActive" HeaderText="Is Active?" />
                </Fields>
            </asp:DetailsView>
            <asp:SqlDataSource ID="EmployeeDetailsDataSource" runat="server"
                ConnectionString="<%$ ConnectionStrings:EmployeeDBConnection %>"

                SelectCommand="SELECT *  FROM Employees WHERE EmployeeId=@EmployeeId"

                UpdateCommand="UPDATE Employees SET FullName=@FullName, Email=@Email, Mobile=@Mobile, Gender=@Gender,
                Salary=@Salary, IsActive=@IsActive 
                WHERE EmployeeID=@EmployeeID"

                DeleteCommand="DELETE FROM Employees WHERE EmployeeID=@EmployeeID"
                >

                <SelectParameters>
                    <asp:QueryStringParameter Name="EmployeeId" QueryStringField="id" Type="Int32" />
                </SelectParameters>
            </asp:SqlDataSource>
        </div>
    </form>
</body>
</html>
