<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="GridViewDemo.aspx.cs" Inherits="DataControlsDemonstration.GridViewDemo" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
        <div>
            <asp:GridView ID="gvEmployees" runat="server"
                AutoGenerateColumns="false" DataKeyNames="EmployeeId"
                DataSourceID="ObjectDataSource1" AllowPaging="true" PageSize="5"
                AllowSorting="true" AutoGenerateEditButton="true" AutoGenerateDeleteButton="true"
                >
                <Columns>
                    <asp:BoundField DataField="EmployeeID" HeaderText="Employee ID" ReadOnly="true" />
                    <asp:BoundField DataField="FullName" HeaderText="Full Name" />
                    <asp:BoundField DataField="Email" HeaderText="Email" />
                    <asp:BoundField DataField="Mobile" HeaderText="Mobile" />
                    <asp:BoundField DataField="DepartmentName" HeaderText="Department" ReadOnly="true" />
                    <asp:BoundField DataField="Salary" HeaderText="Salary" DataFormatString="{0:C}" />
                    <asp:CheckBoxField DataField="IsActive" HeaderText="Is Active?" />
                </Columns>
              
            </asp:GridView>

           <%-- <asp:SqlDataSource runat="server"
                ID="EmployeeSqlDataSource" 
                ConnectionString="<%$ ConnectionStrings:EmployeeDBConnection %>"

SelectCommand="SELECT E.EmployeeID, E.FullName, E.Email,E.Mobile,D.DepartmentName,E.Salary,
                E.IsActive FROM Employees E
                INNER JOIN Departments D ON E.DepartmentID = D.DepartmentID"

                UPDATECOMMAND="UPDATE Employees SET FullName=@FullName, Email=@Email, Mobile=@Mobile, Salary=@Salary, IsActive=@IsActive 
                WHERE EmployeeID=@EmployeeID"

                DeleteCommand="DELETE FROM Employees WHERE EmployeeID=@EmployeeID"
                />--%>
            <asp:ObjectDataSource ID="ObjectDataSource1" runat="server"
                TypeName="DataControlsDemonstration.Services.EmployeeService"
                SelectMethod="GetEmployees"
                >


            </asp:ObjectDataSource>

        </div>
    </form>
</body>
</html>
